### ISSUE TITLE
Search bar with Select Drop down Menu

### ISSUE THREAD

**Issue by SamSwartzPB** [PBGUX/designsystem#10]
Currently there's no way to implement a select drop down into a search bar and have it show alternate search options. Dropdown action on search doesn't replace text after click.

![screen shot 2015-02-06 at 3 55 25 pm](https://cloud.githubusercontent.com/assets/10424009/6087383/ac0756ee-ae18-11e4-8069-e7e00211e273.png)

Using standard select HTML results in some unpleasant breaks in firefox.

![screen shot 2015-02-06 at 9 12 55 am](https://cloud.githubusercontent.com/assets/10424009/6087332/29357656-ae18-11e4-87a1-32dcd40f0063.png)

**Comment by lombardi-gux** [comment]
this is a quick, rough idea, but how about this?  
http://plnkr.co/edit/mjBN2QQ8a7c87hnQOAun?p=preview

tested in chrome and FF

**Comment by smlombardi** [comment]
Sam, can you please comment if the proposed solution works for you?

**Comment by SamSwartzPB** [comment]
@lombardi-gux This looks good to me Steve - thanks for taking a look :smile:
