### ISSUE TITLE
Selection from a large list

### ISSUE THREAD

**Issue by fondo213** [PBGUX/designsystem#104]
Hello Design System people!
Request for Spectrum Spatial Manager that I suspect might be useful elsewhere. The welie library calls it a "parts selector".  
http://www.welie.com/patterns/showPattern.php?patternID=parts-selector

Dual listbox - left side contains a list of items, right side is the items selected from that list. Buttons in the middle to Add, Add All, Remove, Remove All. 
In our application user is selecting 1 to n columns from a table. There can be dozens of columns. The only multiple selection control I see in the Design Sysetm is the 'multi-row select menu with checkboxes' which I don't think is appropriate for lists bigger than say 10ish.

**Comment by smlombardi** [comment]
The link does not load for me.  Do you have a screenshot?

**Comment by fondo213** [comment]
<img width="485" alt="screen shot 2016-04-08 at 1 19 49 pm" src="https://cloud.githubusercontent.com/assets/10961179/14391916/adf19a5e-fd8c-11e5-96aa-3616b6474df4.png">

**Comment by fondo213** [comment]
This is from an Axure prototype I built. To reiterate though, in the case the request is for the number of things in the lift listbox can be pretty big - dozens.

**Comment by fondo213** [comment]
<img width="658" alt="screen shot 2016-04-08 at 1 22 15 pm" src="https://cloud.githubusercontent.com/assets/10961179/14391956/f2ec30d8-fd8c-11e5-98c2-18b7aca36735.png">

**Comment by fondo213** [comment]
second one is from eTrade (and it's not nearly as handsome as our DS).
If this control/pattern gets implemented, I would include the optional UpDown buttons - allow the user to order the list they're building in the right list box. Up/Down should be optional - some folks won't need it.

**Comment by smlombardi** [comment]
Thanks.  This looks like the old "Font/DA Mover" from old versions on Mac OS.

We will add it to the backlog and prioritize it.  Thanks again.

**Comment by fondo213** [comment]
Much obliged.


Dave Fondacaro


Advisory User Experience Designer (IxD)

Global User Experience


T  518.285.7134

M 518.852.1551


dave.fondacaro@pb.com<mailto:dave.fondacaro@pb.com>

pitneybowes.com<file://composeviewinternalloadurl/www.pitneybowes.com>


Pitney Bowes

1 Global View

Troy, NY 12180

**Comment by fondo213** [comment]
Hi Dan,
I got this notification from GitHub, not sure what it means.
The request was for a list-builder (selection from a large list).
Does this "closed" notification mean the the control was built and will be available in a DS release?
D


Dave Fondacaro


Advisory User Experience Designer (IxD)

Global User Experience


T  518.285.7134

M 518.852.1551


dave.fondacaro@pb.com<mailto:dave.fondacaro@pb.com>

pitneybowes.com<file://composeviewinternalloadurl/www.pitneybowes.com>


Pitney Bowes

1 Global View

Troy, NY 12180

**Comment by danielcollettepb** [comment]
Hi Dave, no `closed` does not mean that is is `done`. The JIRA backlog story references this issue and we can `reopen` this once it is prioritized and work is started. (We would also add it to a milestone so you know which release it will be completed in and add an assignee of who will do the work/own the story.)
