### ISSUE TITLE
The text on the dropdown is unreadable 

### ISSUE THREAD

**Issue by sparkhi** [PBGUX/designsystem#11]
http://guxstaging.pbi.global.pvt/design_system/#/elements?section=Buttons

In the Dropdown button, when the dropdown menu is visible, the text on the menu item becomes black in colour, this means the background of the text (dark blue) and the text colour are both dark which makes it really difficult to read. should have some contrast colour

**Comment by lombardi-gux** [comment]
Fixed in version 1.05, see 4f57dfedb277159c8e847289c006200b321db1d0
