### ISSUE TITLE
Shaking, off-centre spinners in FireFox

### ISSUE THREAD

**Issue by cbrunger** [PBGUX/designsystem#114]
Hi,

The loaders are really shaking about and off-centre in Firefox if I look on http://guxstaging.pbi.global.pvt/design_system_staging/#/foundation/nucleo-mini#loaders

they also aren't antialiased by the looks of them. They are fine in Chrome.

Colin

**Comment by nishrana** [comment]
@cbrunger - They look fine on latest Firefox/Mac. What OS and browser version are you using?

**Comment by nishrana** [comment]
Also, the URL that you have is for our staging site. http://guxstaging.pbi.global.pvt/design_system/#/home is the URL for production.

**Comment by cbrunger** [comment]
I was running Firefox 45.0.2 on Windows 10, and checked the production URL with the same result. However, when I checked my browser version it started downloading an update. Once it had updated to version 46.0 the loaders are fixed and smooth again.
Looks like it must have been an issue with that version, not sure why though.

**Comment by nishrana** [comment]
Interesting.. Thanks for the feedback! Closing this issue.
