### ISSUE TITLE
Button style not going away.

### ISSUE THREAD

**Issue by du002cl** [PBGUX/designsystem#12]
Using the control of an input followed by a button, after mouse-release the button stays dark. 

Here it is in context...
![buttonhold](https://cloud.githubusercontent.com/assets/10408154/6155200/664b61c8-b1ff-11e4-9f2e-854f2fe90a8e.png)

Here it is on the live preview..
http://guxstaging.pbi.global.pvt/design_system/#/elements?section=Inputs

Issue arises because we allow a user to submit by pressing enter on the input or clicking the button. So if they submit by button the user is left with the page looking different from if they submit via enter-key.

**Comment by lombardi-gux** [comment]
The problem here is that these buttons do not lose focus unless something else gets focus.  I have modified the focus state to look like the "off" state, so this should no longer be a problem.

See 897adcf5ee1fc16976e3cfa6dcbb10d673071b62
