### ISSUE TITLE
Missing fa-to-nucleo mappings

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/designsystem#123]
I just ran through our icons.  Out of the 88 font awesome icons we are using, only 38 of them are mapped.

Have the new mappings, mentioned in the 2.7 portion of the [changelog](https://github.com/PBGUX/designsystem/blob/master/CHANGELOG.md), been pushed to the [website](http://guxstaging.pbi.global.pvt/design_system/modules/foundation/assets/images/fa-to-nucleo-conversions.pdf)?

**Comment by victorhayes** [comment]
rdukeshier: Can you please give us a list of the 50 icons that are missing so we can add them to the mapping list? Thanks!

**Comment by rdukeshier** [comment]
fa-angle-double-left
fa-angle-double-right
fa-arrow-circle-left
fa-arrow-circle-right
fa-arrow-down
fa-arrow-left
fa-arrow-up
fa-ban
fa-bars
fa-bell-o
fa-bolt
fa-caret-down
fa-caret-right
fa-caret-up
fa-check-square
fa-check-square-o
fa-chevron-down
fa-chevron-left
fa-chevron-right
fa-circle
fa-circle-o-notch
fa-close
fa-columns
fa-comment-o
fa-comments-o
fa-database
fa-edit
fa-eraser
fa-external-link
fa-file-text-o
fa-floppy-o
fa-hdd-o
fa-list-ol
fa-list-ul
fa-minus
fa-mouse-pointer
fa-music
fa-pause
fa-play
fa-plug
fa-sign-in
fa-sign-out
fa-sitemap
fa-spinner
fa-square-o
fa-table
fa-th-large
fa-trash
fa-tree
fa-warning

**Comment by smlombardi** [comment]
This has been updated
