### ISSUE TITLE
Table border is missing when the table is empty (Firefox only)

### ISSUE THREAD

**Issue by th001sy** [PBGUX/designsystem#13]
Note the table header's blue bottom border and the footer's grey top border:

![chrome](https://cloud.githubusercontent.com/assets/11270501/6440537/e1360a0c-c0d5-11e4-9013-1fc964fdc39b.JPG)
(Screenshot from Chrome)

Borders are not displayed in Firefox when the table is empty: 

![firefox](https://cloud.githubusercontent.com/assets/11270501/6440538/e4c5ee58-c0d5-11e4-8f73-aa91133db91e.JPG)
(Screenshot from Firefox)

However once the table is populated the borders are rendered correctly:

![firefox2](https://cloud.githubusercontent.com/assets/11270501/6440540/e644972a-c0d5-11e4-81ba-77e0d99f529f.JPG)
(Screenshot from Firefox)

-------------------
What appears to be happening is bootstrap is setting the table style to be:  "border-collapse: collapse" (the HTML default is "border-collapse: separate" http://www.w3schools.com/cssref/pr_border-collapse.asp ) but Firefox has a long standing history  with this style: 
https://bugzilla.mozilla.org/show_bug.cgi?id=688556
http://forums.mozillazine.org/viewtopic.php?f=25&t=582414
https://wordpress.org/support/topic/firefox-css-trouble

We may choose to ignore it as it's a browser issue, but there are a number of work arounds out there - reverting the style back to "border-collapse: separate" seems to fix the issue with no consequences on the table layout in Chrome, Firefox and IE10 (but that was only a quick check).

**Comment by smlombardi** [comment]
You need to have a THEAD with the TR and the THs in it to get the border.

**Comment by th001sy** [comment]
Thank you for your reply. Unless I'm reading your response incorrectly, then we do already have our tables set up as suggested: 

![markup](https://cloud.githubusercontent.com/assets/11270501/6594683/457c2030-c7db-11e4-9238-57e3480428c3.JPG)

The problem occurs when the array "items" (which is used for 'ng-repeat') is empty, meaning no table rows are created within TBODY. As mentioned in the OP, it is only Firefox (version 36.0.1) which fails to display the table borders in this scenario, therefore I don't think this is an issue with the mark up but a Firefox bug. If I set the border-collapse style back to the default value (as shown below) the table borders will display correctly in all browsers (IE, Chrome and Firefox).

![markup2](https://cloud.githubusercontent.com/assets/11270501/6594754/f284a054-c7db-11e4-833e-28d4ed8a8bd5.JPG)

**Comment by smlombardi** [comment]
I see now, it seems to be an issue with empty ng-repeats.  Might just be a browser bug.

The bootstrap default is border-collapse: collapse for tables, but if separate works in these cases it shouldn't be much harm to override.

**Comment by th001sy** [comment]
Yes, that's correct. A HTML table is styled "border-collapse: separate" by default, but bootstrap is overriding the value to be "border-collapse: collapse" - a style/setting Firefox is known to have issues rendering.

As we've said, one potential solution is to revert bootstrap's change back to the HTML default. I have  tested this solution on my local machine with tables I've helped develop and they look to be behaving correctly in Chrome, IE and Firefox. However I'd be wary of somebody implementing this change in to the Design System without prior testing to confirm all tables will behave as expected with this change.

Thank you for your time.
