### ISSUE TITLE
Minor web site issue with section titles

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/designsystem#138]
I could be wrong but I think that the titles for the small form and large form are reversed:  http://guxstaging.pbi.global.pvt/design_system/#/patterns/forms

**Comment by smlombardi** [comment]
Correct.  That's odd.

**Comment by danielcollettepb** [comment]
@smlombardi can you confirm that this is fixed?

**Comment by danielcollettepb** [comment]
confirmed that this is fixed
