### ISSUE TITLE
Side Menu Rounded Corners

### ISSUE THREAD

**Issue by SamSwartzPB** [PBGUX/designsystem#14]
Anchor tags with the class "list-group-item" get rounded corners on the last child of the list for both hover and active states

![screen shot 2015-03-03 at 2 38 32 pm](https://cloud.githubusercontent.com/assets/10424009/6470655/2f9438c6-c1b3-11e4-929a-d88948e8780a.png)

**Comment by lombardi-gux** [comment]
This is as designed.
