### ISSUE TITLE
sliding tabs only work for 4 tabs

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/designsystem#140]
Unless I am missing something the CSS for the sliding tabs only works if there are 4 tabs even though the width for the tab is set to 20% which would indicate it is designed for 5 tabs.  In our case we have 6 so the selected tab indication is off by 2 tabs.

**Comment by smlombardi** [comment]
You are correct.  Sam, the creator of the sliding tabs is working on developing it in a way to make it easier to add more tabs.  We will take a look.

**Comment by jrnorrisjr** [comment]
I adding the fancy-tab css to the application's css and modified it to change the width and added two more nth-child transforms and got it to work.

**Comment by danielcollettepb** [comment]
This is updated in DS 3.0 and will work with up to 6 sliding tabs.
