### ISSUE TITLE
Unsupported browser example does not work

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/designsystem#141]
I tried to add the unsupported browser example to our application and have some issues.

In the unsupported.html file it references main.css which I can't find.  It also references a controller even though it is not an angular app.

It provides no support for localization.  It probably should use the browser setting to do that.

Running IE in IE9 emulation mode gives a 404 response for URL = http://guxstaging.pbi.global.pvt/design_system/unsupported.html

**Comment by danielcollettepb** [comment]
This is now a static HTML file in 3.0, you can find it here:

https://github.com/PBGUX/designsystem-3/blob/develop/app/unsupported.html
