### ISSUE TITLE
data-widget-icon not centered in IE 11 

### ISSUE THREAD

**Issue by shawnss** [PBGUX/designsystem#143]
The icon in data widget is centered in Chrome and Firefox but not in IE 11. See attached images.
![datastyle-chrome](https://cloud.githubusercontent.com/assets/7524790/16784281/0585c60a-4856-11e6-92d5-c65d4bd9186c.PNG)
![datastyle-ie11](https://cloud.githubusercontent.com/assets/7524790/16784286/0a11379a-4856-11e6-9bac-c3d094ed455f.PNG)

**Comment by smlombardi** [comment]
Should be fixed in 3.0
