### ISSUE TITLE
Date Range - selecting 'To' field selects 'From' date

### ISSUE THREAD

**Issue by rcianfag** [PBGUX/designsystem#145]
Date Range bug
On returning to a custom date range, selecting 'To' field selects 'From' date

Steps to reproduce
select From and To custom date range
open with custom date range
Select 'To' field - to change just the 'To' date e.g. expanding from Sept 1 to Sept 4
Focus goes to 'To' field, but selection clears date range and changes 'From' date to current selection

Expected
Selecting 'To' field would allow me to change just the 'To' date (like Google Flights).
![date picker](https://cloud.githubusercontent.com/assets/11758386/17302064/58cde738-57e8-11e6-95de-3d0f6ae61396.png)

**Comment by danielcollettepb** [comment]
Per the plugin author, this is the intended design. This is not a DS issue, you can look for another plugin that functions the way you want and let us know what you find out so we can add it to the DS:

https://github.com/dangrossman/bootstrap-daterangepicker/issues/781
