### ISSUE TITLE
Date Range - no 'Show All' selection

### ISSUE THREAD

**Issue by rcianfag** [PBGUX/designsystem#146]
There is no 'Show all' selection.
We had to create a pre-defined wide date range to show all results.

Should be a way to remove all filters.

**Comment by danielcollettepb** [comment]
You would have to provide a button in the UI to `Show All` and reset the date range to the initial state (the wide range).

**Comment by rcianfag** [comment]
Yep - that is what we did, 'All dates' is a predefined wide custom date range. We wanted to let you know of the need to show all.


![screen shot 2016-08-01 at 2 20 48 pm](https://cloud.githubusercontent.com/assets/11758386/17304346/394e7836-57f3-11e6-84f1-91949a4b6be5.png)

**Comment by danielcollettepb** [comment]
OK, thanks... this is up to each app to decide if they need it.
