### ISSUE TITLE
a.list-group-item gets weird styling

### ISSUE THREAD

**Issue by SamSwartzPB** [PBGUX/designsystem#15]
![image](https://cloud.githubusercontent.com/assets/10424009/6513403/c8d8ac42-c348-11e4-8c0b-6113683cb5e7.png)

^^^ when there is an a.list-group-item it gets wrong font size, color, and also wrong type treatment. Internally I'm fixing this with a global style, but that shouldn't be a permanent solution

This is what I'm currently using to fix the problem
<pre><code>
//FIXME: This should be handled in design systems - talk to Steve
a.list-group-item {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
		font-weight: normal;
		color: #4e4e4e;
}
</code></pre>

**Comment by smlombardi** [comment]
Fixed in 2ea204f8107f639ef8c85b13531d8cfc3dc21558

It was _links_ in list groups that BS incorrectly styled.
