### ISSUE TITLE
Selectize Border overrides error state

### ISSUE THREAD

**Issue by SamSwartzPB** [PBGUX/designsystem#17]
When the selectize gets the .has-error class, it's overwritten by the default styles. So even though there's an error state, the border outline is still grey rather than red. Screenshot attached

![screen shot 2015-04-23 at 2 26 22 pm](https://cloud.githubusercontent.com/assets/10424009/7304393/344ad958-e9c5-11e4-948f-2632f15dbafd.png)

**Comment by smlombardi** [comment]
![screen shot 2015-05-05 at 12 33 40 pm](https://cloud.githubusercontent.com/assets/835148/7477681/71539cec-f323-11e4-8131-7390a3be933f.png)
