### ISSUE TITLE
Helvetica Neue font misbehaving in PC

### ISSUE THREAD

**Issue by SamSwartzPB** [PBGUX/designsystem#18]
Getting some weird treatment for Helvetica Neue on Bob Moorehouse's PC. He's using chrome, but the font sizes look wonky - check out the "r's" specifically in the H4's on the screenshot. Might need some additional font smoothing properties on body/header tags using Helvetica Neue

***Note: When I opened up his dev tools and took off the helvetica neue font in in the font family, plain helvetica was fine. Also, saw no issue with precision sans.

![warner bros font issue](https://cloud.githubusercontent.com/assets/10424009/7304492/caf1e842-e9c5-11e4-9bb9-55a6838e3fff.JPG)

**Comment by smlombardi** [comment]
we already reset font smoothing to browser defaults.  this is likely a font conflict issue on that pc.  please test on other pcs, and also in IE11 on the PC.

Can you also provide me (off-github) with the URL for me to test?

**Comment by smlombardi** [comment]
No response for over 4 months, assumed fixed.
