### ISSUE TITLE
Numeric stepper truncating displayed value in IE 10

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/designsystem#19]
If you manually type a numeric value, it get's truncated in the view when the control loses focuses in IE 10.  In the following Live Preview screenshot, I manually entered 12345 into the stepper:

![image](https://cloud.githubusercontent.com/assets/5713608/7622757/2677a756-f998-11e4-95af-349592a10603.png)

Everything is displayed fine if the stepper buttons are used to change the value.

**Comment by danielcollettepb** [comment]
Looks like this is a known issue with the IE10 clear X in the input:

http://stackoverflow.com/questions/19291044/ie-10-cuts-off-text-in-text-box-after-100-px

You can temporarily add the `::-ms-clear` css to your project, we'll add this in the next DS update. Thanks for letting us know

**Comment by smlombardi** [comment]
This is in 2.0 CSS
