### ISSUE TITLE
Issues with Twitter Typeahead

### ISSUE THREAD

**Issue by ldaug** [PBGUX/designsystem#21]
I updated to 2.0 today and am having some issues with the twitter type-ahead control (0.10.5). The issue is that the drop down shifts:

![image](https://cloud.githubusercontent.com/assets/7534439/9619091/34ab403c-50da-11e5-9fb8-7754701c9e38.png)

I reverted the update to DS, and it began working again. After trying to figure out the issue I believe it has to do with placing the type-ahead in a input-group. This only appears to be an issue in Chrome.

**Comment by smlombardi** [comment]
Can you please provide a link to this component?

**Comment by ldaug** [comment]
1) Open http://lu002da-lan7:8080/hub-browser/#/discovery in Chrome (I have latest build)
2) Login admin\admin
3) On Model page choose any model
4) Switch to Discovery page
5) Enter some text
6) Click backspace until text is erased
7) Input control will shift up
8) If this does not happen, enter some text again
9) Input will shift down

**Comment by smlombardi** [comment]
Thanks.  I meant the twitter type-ahead, is it a Bower component?

**Comment by ldaug** [comment]
It is. We use it along with handlebars.js

	  "typeahead.js": "0.10.5",
	  "handlebars": "1.3.0"

The version is not the latest as the change log indicates v11 is a overhaul and should be considered as a beta.

https://twitter.github.io/typeahead.js/
http://handlebarsjs.com/

**Comment by danielcollettepb** [comment]
I tested in chrome and see the issue, but not related to the DS. Try the following:

In the .twitter-typeahead class, remove the display: block !important;
![image](https://cloud.githubusercontent.com/assets/6116867/9666176/94a5fdba-5242-11e5-83fb-81be16787fb7.png)

Then chrome looks OK
![image](https://cloud.githubusercontent.com/assets/6116867/9666222/daf5e8de-5242-11e5-9c24-baf8aa2a1f69.png)

Thanks for the detailed info and login... really helpful to troubleshoot!

Let us know if this works and we'll close the issue.

**Comment by ldaug** [comment]
Yea, that works. Actually thought I tried taking that out, but must of missed something. I copied this css from a example, and the full line for that lines is:

.twitter-typeahead, .tt-hint {
  width: 100%;
  display: block !important;  /* twitter typeahead has an inline style that sets the to inline-block that looks bad in IE */
}

So I checked IE after the change and now it's not aligned correctly.

![image](https://cloud.githubusercontent.com/assets/7534439/9666496/5ea31840-5244-11e5-9345-8dbaf93fd74e.png)

**Comment by danielcollettepb** [comment]
Which version of IE?

**Comment by ldaug** [comment]
11.0.96

**Comment by ldaug** [comment]
I added a class to override the display and that seems to fix issues across the board.

.browser-typeahead {
  display: inline !important;   /* Fixes alignment issues in IE */
}
```
          <div id="discoveryTypeAhead" class="input-group before" >
            <span class="input-group-addon"><i class="fa fa-search"></i></span>
            <input id="discoveryInput" class="typeahead form-control browser-typeahead" type="text" ng-trim="false">
            <span div="prevButton" class="input-group-addon" style="padding: 0px"><a id="previousPageButton" class="btn btn-primary btn-sm btn-default" ng-click="discovery.paging.previousPage()" ng-class="{disabled:!discovery.paging.hasPreviousPage || discovery.busy}" ><i class="fa fa-chevron-left" /></a></span>
            <span div="nextButton" class="input-group-addon" style="padding: 0px"><a id="nextPageButton" class="btn btn-primary btn-sm btn-default" ng-click="discovery.paging.nextPage()" ng-class="{disabled:!discovery.paging.hasNextPage || discovery.busy}"><i class="fa fa-chevron-right" /></a></span>
          </div>
```

**Comment by danielcollettepb** [comment]
Thanks @ldaug, glad you figured this out.
