### ISSUE TITLE
Navbar troubles

### ISSUE THREAD

**Issue by SamSwartzPB** [PBGUX/designsystem#22]
In some versions of DS2 navbars the "dot" class has been applied to an icon. Looks like it's an image behind the link that's creating the dot effect. 

In Horizon we have a dropdown on the help icon and the magenta background image still shows - maybe the current image could be replaced with a grey version with transparency? That way it'll look good on the white background and anywhere else on the navbar that it might be applied.

<img width="305" alt="screen shot 2015-09-02 at 4 17 41 pm" src="https://cloud.githubusercontent.com/assets/10424009/9663538/f4041946-5232-11e5-96a5-118aba0158e7.png">

**Comment by smlombardi** [comment]
The dot class has been removed.  Icons are all now one piece, and menus are included in the headers section.

![screen shot 2015-09-16 at 3 02 50 pm](https://cloud.githubusercontent.com/assets/835148/9915255/120a0b52-5c84-11e5-8e61-84bd74cec128.png)
