### ISSUE TITLE
Background image for "dot" class

### ISSUE THREAD

**Issue by nishrana** [PBGUX/designsystem#23]
Design System team,

Great job guys! I love the DS 2.0 website.
I would like to ask for an image asset, particularly the background image for "dot" class. It would be really helpful if you could make it available in pbfont or variable.scss file so that we could reuse in various instances.

Much Appreciated.

Thanks
Nisha

**Comment by smlombardi** [comment]
You can use the "dot" class on any object to put the dot in the background. As a font, you can use fa-circle.  http://fortawesome.github.io/Font-Awesome/icon/circle/

**Comment by smlombardi** [comment]
The dot class has been removed for 2.1 release.  We are now using solid icons, all one piece font or svg.
