### ISSUE TITLE
Focus states for form items like radios and checkboxes

### ISSUE THREAD

**Issue by smlombardi** [PBGUX/designsystem#24]
We are wanting to use keyboard navigation on some things in Horizon. Currently, it doesn’t look like there are focus states for radios or checkboxes. I’m not sure if this is something you guys want in DS 2.0, or not.

I created a story for Sam on our Jira board for what we need in the shipping app (toolbar icons, radios & checkboxes). Here’s the link for reference: http://jira.pbi.global.pvt/browse/HORSHIP-5323

**Comment by danielcollettepb** [comment]
this will get in the next release, working offline with Sam on bugs
