### ISSUE TITLE
Misalignment, when a button is placed right next to an input field.

### ISSUE THREAD

**Issue by nishrana** [PBGUX/designsystem#26]
![image](https://cloud.githubusercontent.com/assets/9932055/9936013/f3b9dea8-5d27-11e5-8c7f-6cbface733f7.png)

I noticed that there's a slight misalignment when a button (which uses class btn) was placed next to an input field. The default line-height for buttons should probably match the input fields/ form-control class.

**Comment by danielcollettepb** [comment]
steve fixed this issue, will be in 2.1.0 release
