### ISSUE TITLE
Focus on Inputs doesn't look like it's getting the right color red

### ISSUE THREAD

**Issue by SamSwartzPB** [PBGUX/designsystem#27]
Form inputs look like they're getting default Bootstrap styling - focus color is too dark and there also looks like theres a shadow being added

![image](https://cloud.githubusercontent.com/assets/10424009/10003904/da7cd686-607c-11e5-8b1a-2569937bf5cc.png)

**Comment by smlombardi** [comment]
Fixed in ffc2c3c12df291f615a19f44c73e485e59de070f
