### ISSUE TITLE
modal-content 60 px padding?

### ISSUE THREAD

**Issue by shawnss** [PBGUX/designsystem#31]
Is it necessary to have 60 pixels padding for the modal content? Here is what it looks like. 
Thanks,
Shawn

![image](https://cloud.githubusercontent.com/assets/7524790/10108332/4de7fd80-638e-11e5-87e7-25388bffd079.png)

**Comment by danielcollettepb** [comment]
Thanks Shawn, sent to the team to review

**Comment by shawnss** [comment]
Thanks. It don't look to bad if just used as a message box but when there are more controls on it then it looks too much in my eyes. Here is another sample.
![image](https://cloud.githubusercontent.com/assets/7524790/10109483/2b82a978-6395-11e5-8894-15f4391529e0.png)

**Comment by victorhayes** [comment]
Hi Shawn, the 60 pixel margin is necessary. I gives adequate spacing from the edges, especially for the second example you sent (w/form fields). To tighten the margins is to remove the air (white space) and visually suffocate the content (making it feel too enclosed).  Also, the "OK" and "Cancel" should be moved over so the "OK" button is left aligned with the form fields.

**Comment by danielcollettepb** [comment]
the visual style is correct, no changes needed
