### ISSUE TITLE
Versioning for CSS

### ISSUE THREAD

**Issue by nishrana** [PBGUX/designsystem#32]
Can you please provide a version number on top of the CSS file to track the updates. Also, release notes would be helpful to see what changes were pushed for every CSS update.

Thanks
Nisha

**Comment by smlombardi** [comment]
Added banners to CSS files as of f53e02555dc5bf24b7b5940df6237935a2a00569

See:

![screen shot 2015-10-06 at 9 01 00 am](https://cloud.githubusercontent.com/assets/835148/10309179/1d687422-6c09-11e5-9d69-4fd393bab4e4.png)
