### ISSUE TITLE
In Progress button - enabled version

### ISSUE THREAD

**Issue by rcianfag** [PBGUX/designsystem#33]
Hi - in Fireball, we need to include a button label on the in-progress button, and the disabled state is heard to read.

We would like to use the enabled state color, but make the button disabled, so that the user knows it's working on request.

<img width="361" alt="screen shot 2015-10-16 at 12 59 15 pm" src="https://cloud.githubusercontent.com/assets/11758386/10548000/c84a2e4a-7405-11e5-9507-1061a745638a.png">

<img width="200" alt="screen shot 2015-10-16 at 12 58 36 pm" src="https://cloud.githubusercontent.com/assets/11758386/10548021/e025391a-7405-11e5-8ff6-68d004aa87b2.png">

<img width="192" alt="2- save and print" src="https://cloud.githubusercontent.com/assets/11758386/10548056/46a40144-7406-11e5-9b6c-3fb54fbabd4d.png">

![saving and printing](https://cloud.githubusercontent.com/assets/11758386/10548293/8f301208-7407-11e5-9802-b35e4b8ee5c8.png)

**Comment by danielcollettepb** [comment]
@rcianfag I know we discussed this with @victorhayes a few weeks ago... Is there anything outstanding on this item? If not I will close this issue. Thanks!

**Comment by victorhayes** [comment]
The disabled state shown is incorrect. See DS:  guxstaging.pbi.global.pvt/design_system/#/buttons

**Comment by danielcollettepb** [comment]
issue was resolved in the application
