### ISSUE TITLE
fa-lg issue with pb-font icons

### ISSUE THREAD

**Issue by dustin2524** [PBGUX/designsystem#35]
We have a `button-group` full of icons using `fa-lg`. The style looks fine, until we introduce an icon from pb-fonts. Then the pb-font icon is slightly bigger than the rest. 

I reproduced this in the design system site by going to the toolbar button example and adding fa-lg to each icon, then changing one to a pb-icon. See here:

![image](https://cloud.githubusercontent.com/assets/4664726/10741653/414eb1ca-7bff-11e5-9c92-10964b280ebe.png)

If I remove the designsystem rule that applies the 1.5em font-size to .fa-lg then the issue is resolved. Not sure if its the right solution but its my temporary fix.

![image](https://cloud.githubusercontent.com/assets/4664726/10741665/4ebfc90c-7bff-11e5-85f2-1e00ec2c862b.png)

**Comment by danielcollettepb** [comment]
Thanks @dustin2524, adding this as high priority to fix

**Comment by smlombardi** [comment]
Fixed in https://github.com/PBGUX/designsystem/commit/91c96ee76689ff4b65fcafd5b804faa955a10152

However, please note that the correct way to use a PB icon is: `<i class="pb-newfolder pb-lg"></i>`

**Comment by dustin2524** [comment]
Looking at the fix I see the fa-lg rule is still there. Is there any chance that can get deleted? Now all our fa-lg icons are larger than we'd like them, the rule font-awesome did with their class `fa-lg` seemed better.

**Comment by lombardi-gux** [comment]
The fa-lg class is for font awesome icons only, to get a larger variant.

The new pb-lg class is to do the same with pb-font.

We hope to better streamline pb font in the future.

From: dustin2524
Reply-To: PBGUX/designsystem
Date: Tuesday, October 27, 2015 at 12:12 PM
To: PBGUX/designsystem
Cc: Steve Lombardi
Subject: Re: [designsystem] fa-lg issue with pb-font icons (#35)


Looking at the fix I see the fa-lg rule is still there. Is there any chance that can get deleted? Now all our fa-lg icons are larger than we'd like them, the rule font-awesome did with their class fa-lg seemed better.

—
Reply to this email directly or view it on GitHub<https://github.com/PBGUX/designsystem/issues/35#issuecomment-151554113>.

________________________________

**Comment by dustin2524** [comment]
Thanks for the response Steve. I understand that only `fa` icons should use `fa-lg`. The problem is that we have a lot of cases where we chose to use `fa-lg` because it was a good size. But now DS 2.0 has made all those icons slightly too big for us and it's better for us to just override the designsystem's `fa-lg` rule back to font-awesome's original value.

**Comment by smlombardi** [comment]
pb-lg does more than adjust the size.  it fixes the line height and
vertical alignment so the button won't poke out, as it the original bug.

**Comment by dustin2524** [comment]
Not `pb-lg`, im talking about the `fa-lg` rule

    .fa-lg {
       font-size: 1.5em;
     }

**Comment by danielcollettepb** [comment]
@dustin2524 we had to tweak the values for the pb icons to be relatively the same size as fa icons, so rather than override fa, we think a class specific for the pb font will prevent issues with fa icons. Here is a screenshot and some sample markup:

![image](https://cloud.githubusercontent.com/assets/6116867/10822441/a99c732c-7e2d-11e5-989a-6bb3ad48035c.png)


```html
<div class="btn-group">
  <div class="btn-group">
    <button class="btn btn-default" type="button">
      <i class="fa fa-commenting fa-lg"></i>
    </button>
  </div>
  <div class="btn-group">
    <button class="btn btn-default" type="button">
      <i class="pb-newfolder pb-lg"></i>
    </button>
  </div>
</div>
```

We are starting work on a custom font icon set aligned with our brand, so this is great feedback of things we need to watch out for... Thanks!

**Comment by dustin2524** [comment]
@danielcollettepb I understand, and agree than fa shouldnt be overridden, which is why I am suggesting we delete the fa-lg rule that the design system has. Our font awesome icons looked better when we were just using font-awesome's fa-lg class

**Comment by danielcollettepb** [comment]
@dustin2524 there is not enough of a size difference between a regular fa icon and and fa-lg icon, so we had bumped the fa-lg font-size from 1.333 to 1.5, so we need to keep the CSS for this in the Design System.

**Comment by dustin2524** [comment]
@danielcollettepb I do not think this was the case for our app. That's fine though, when we use the new use the new pb-lg class and see how pb icons look next to our fa icons then we'll reaccess and override rules if needed. Thanks for the feedback.
