### ISSUE TITLE
Selectize-input always showing dropdown-arrow

### ISSUE THREAD

**Issue by dustin2524** [PBGUX/designsystem#36]
We have a control that uses selectize input but does not have a dropdown.
![image](https://cloud.githubusercontent.com/assets/4664726/10762584/118b1124-7c9d-11e5-83a4-51d91f4c69e2.png)

As of DS 2.0 there is now a dropdown arrow because of the rule...

    .selectize-input:after {
        content: ' ';
        display: block;
        position: absolute;
        top: 50%;
        right: 17px;
        margin-top: -3px;
        width: 0;
        height: 0;
        border-style: solid;
        border-width: 5px 5px 0;
        border-color: #333 transparent transparent;
    }

The selectize css already comes with this rule, but slightly more targeted, which is good for us because it wasnt matching our input without a dropdown.

    .selectize-control.single .selectize-input:after {
        content: ' ';
        display: block;
        position: absolute;
        top: 50%;
        right: 17px;
        margin-top: -3px;
        width: 0;
        height: 0;
        border-style: solid;
        border-width: 5px 5px 0 5px;
        border-color: #333333 transparent transparent transparent;
    }

As always, we have no problem overriding this rule if thats what we have to settle with.

**Comment by danielcollettepb** [comment]
This is an application specific issue, you can override as needed.

**Comment by dustin2524** [comment]
@danielcollettepb Is the designsystem supporting the selectize control? If no then I dont see any need for this css rule. If yes then it seems kind of odd to consider it application specific since the main demo on the selectize page falls under this category. 

https://brianreavis.github.io/selectize.js/

**Comment by danielcollettepb** [comment]
@dustin2524 we have dropped support of selectize.js and have switched to [ui-select](https://github.com/angular-ui/ui-select) as it is a native Angular control. Feedback from teams was that selectize.js was difficult to work with and unit test, if I remember correct it had to do with no access to the model in the tests. The new control is on the DS site under Web > UI Controls > Dropdowns (Advanced Select Menus header) and there is an example of tokens with no dropdown icon.

We also have on the backlog to include support for [ngTagsInput](http://mbenford.github.io/ngTagsInput/). Work has been done in a product that we will consume into the DS.

Thanks for following up on this... I should have been clearer on the reason why we don't support selectize.js.

**Comment by dustin2524** [comment]
Thanks @danielcollettepb , you were not lied to, that control was a bit of a pain to work with. 

ngTagsInput looks very nice for what we need as well, looking forward to it.

**Comment by danielcollettepb** [comment]
We can grab the Sass/CSS from the other project as an interim solution. Not sure if all cases are accounted for but I know the tokens have been styled at least. Let me know if this would help and I'll get it for you.

**Comment by dustin2524** [comment]
Thanks but no need for to rush. I think for our current release schedule we are going to leave the controls we have as-is. Hopefully our next release we go thru and update our tag-like inputs (next year).

**Comment by danielcollettepb** [comment]
We have added ngTagsInput and styled it similar to ui-select, will be in next release (targeting 12/15/15)

![image](https://cloud.githubusercontent.com/assets/6116867/11312383/a4927232-8fa3-11e5-911d-97bb7d2bdfd2.png)

**Comment by dustin2524** [comment]
Great to hear, thanks again.
