### ISSUE TITLE
Support for tabs-left/vertical tabs

### ISSUE THREAD

**Issue by dustin2524** [PBGUX/designsystem#37]
We are using [vertical-tabs](https://github.com/dbtek/bootstrap-vertical-tabs) and as of DS 2.0 they look a little odd.

![image](https://cloud.githubusercontent.com/assets/4664726/10763104/0f6ebd08-7c9f-11e5-81e5-2d16b0c2251c.png)

The cause of this is the rule:

    .nav-tabs > li {
        float: left;
        margin-bottom: -1px;
    }

After removing above rule:
![image](https://cloud.githubusercontent.com/assets/4664726/10763168/4447916c-7c9f-11e5-9207-9d495e130701.png)

This rule also seems to be causing border issues

    .nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
        color: #2e2e2e;
        background-color: #fff;
        /* border: 1px solid #e1e1e1; */
        border-top: 2px solid #3e53a4;
        /* border-bottom-color: transparent; */
        cursor: default;
    }

The commented out ones are the changes  I made to make it look slightly better.

![image](https://cloud.githubusercontent.com/assets/4664726/10763326/e8d153c6-7c9f-11e5-82eb-bda289c15c80.png)

Sorry if I am mistaken but believe the previous design system site had an example using vertical tabs.

**Comment by danielcollettepb** [comment]
Will raise this item with the team.

**Comment by danielcollettepb** [comment]
@dustin2524 : can you supply a full screenshot?

**Comment by dustin2524** [comment]
Sure can @danielcollettepb 

![image](https://cloud.githubusercontent.com/assets/4664726/10917829/b78d4860-8230-11e5-82fc-f93c8fcdcda6.png)


That vertical tabs list is only 2, it could be N tabs.

**Comment by danielcollettepb** [comment]
Thanks @dustin2524, we discussed today and the vertical tabs will not be supported in DS. Carla will reach out to you to discuss alternative solutions.
