### ISSUE TITLE
Alerts have 2 close buttons

### ISSUE THREAD

**Issue by dustin2524** [PBGUX/designsystem#38]
We are using the [alert directive in uibootstrap](https://angular-ui.github.io/bootstrap/#/alert).

    <div alert type="danger" close="closeMessage()">error message</div>

The directive is set up such that if the `close` attribute is present then it puts an 'x' there for us. Since you guys also create an 'x' in this case then we have 2 'x's stacked ontop of each other.

![image](https://cloud.githubusercontent.com/assets/4664726/10770963/7e924c48-7cc4-11e5-8e12-a88f9273180a.png)

**Comment by danielcollettepb** [comment]
OK, we see the issue... uibootstrap templates add the `<span>` with the close character. We will add examples to the page and hide the span in CSS... Will keep you posted. Thanks again!

**Comment by danielcollettepb** [comment]
Fixed and will be in next release (targeting 12/15/15)

![image](https://cloud.githubusercontent.com/assets/6116867/11338779/11921726-91c4-11e5-897d-c3bd18f53b50.png)
