### ISSUE TITLE
Disabled Link Buttons

### ISSUE THREAD

**Issue by dustin2524** [PBGUX/designsystem#39]
Sorry in advance if this is the intended behavior. When a link button is disabled it no longer looks like a link button.

This is what we have before:
![image](https://cloud.githubusercontent.com/assets/4664726/10771499/83eee0a4-7cc7-11e5-9037-bef6de1d7321.png)

Now it looks like this:
![image](https://cloud.githubusercontent.com/assets/4664726/10771513/93188062-7cc7-11e5-84eb-4541a7536e41.png)

**Comment by smlombardi** [comment]
Fixed in https://github.com/PBGUX/designsystem/commit/baa7fea1ba8afa722c91a08b98e86bcc3338f325
