### ISSUE TITLE
Color Selection not matching colors

### ISSUE THREAD

**Issue by dustin2524** [PBGUX/designsystem#40]
I was using the Colors page in the DS App and got to this section:

![image](https://cloud.githubusercontent.com/assets/4664726/10849895/538bf17a-7ef9-11e5-981d-fe8db8102c5a.png)

![image](https://cloud.githubusercontent.com/assets/4664726/10849942/91b667c8-7ef9-11e5-9d07-66dad0e23583.png)

None of those hex codes match the color of the background they are on.

**Comment by smlombardi** [comment]
This has been fixed for  a while.  Coming in 2.2.0 update later today.
