### ISSUE TITLE
Text Color Change

### ISSUE THREAD

**Issue by victorhayes** [PBGUX/designsystem#42]
On Helpers Page: 
Change text color to #4e4e4e on Contextual Backgrounds section - #717171 does not have high enough contrast.

**Comment by smlombardi** [comment]
Where is this located?  please provide URL

**Comment by victorhayes** [comment]
@smlombardi 
http://guxstaging.pbi.global.pvt/design_system/#/helpers
- The Contextual Background Colors section

**Comment by smlombardi** [comment]
Uses Bootstraps body text color, which we have made #717171. Still looking for simple solution.

**Comment by smlombardi** [comment]
Tracked down, fixed in https://github.com/PBGUX/designsystem/commit/d70af6c4cdf8702b50eb9bc4a710a0c81b994642
