### ISSUE TITLE
On the Color page: Change BG4 Hex Color

### ISSUE THREAD

**Issue by victorhayes** [PBGUX/designsystem#43]
- Change #E4E6FA to #D8DBF1
- In Bower, please change the "Active Color" for tables from #C5CBE3 to #D8DBf1

**Comment by smlombardi** [comment]
First part is done.  @danielcollettepb Not sure what the second part entails

**Comment by smlombardi** [comment]
Fixed in https://github.com/PBGUX/designsystem/commit/0000e64e81d26d3853506a405bff404f889f5dfd

**Comment by smlombardi** [comment]
@danielcollettepb: In Bower, please change the "Active Color" for tables from #C5CBE3 to #D8DBf1

**Comment by danielcollettepb** [comment]
@victorhayes what do you mean by changing the active color in "Bower"

**Comment by victorhayes** [comment]
So. Sam said that in Bower the selected state color for table rows is #C5CBE3 when it should be #D8DBf1

**Comment by danielcollettepb** [comment]
OK, that change will happen in Bower when the next release is done. This is part of the release workflow and not an individual task. Since the change is done here by @smlombardi, marking this as closed.

**Comment by victorhayes** [comment]
ok
