### ISSUE TITLE
On Typography page: Breadcrumb spec (text colors) in Navigation table incorrect

### ISSUE THREAD

**Issue by victorhayes** [PBGUX/designsystem#45]
- Breadcrumbs (current page) - C0C0C0
- Breadcrumbs (previous pages) - 0072B8
- Breadcrumbs (hover) - 005A93

**Comment by smlombardi** [comment]
Fixed in https://github.com/PBGUX/designsystem/commit/0000e64e81d26d3853506a405bff404f889f5dfd
