### ISSUE TITLE
Contextual State Panels

### ISSUE THREAD

**Issue by dustin2524** [PBGUX/designsystem#47]
[We use contextual bootstraps panel headers](http://getbootstrap.com/components/#panels-alternatives)

![image](https://cloud.githubusercontent.com/assets/4664726/11076094/e4a7e9cc-87c6-11e5-9ed0-a6ad7b0019e1.png)

Worked fine before.

What it looks like by removing the margin that was added

![image](https://cloud.githubusercontent.com/assets/4664726/11076138/2f501684-87c7-11e5-880a-062e0b9b3853.png)

**Comment by danielcollettepb** [comment]
We have a panel-filled-header but it adds a gray background so you still can't use the contextual alternates. Will work on a fix.

```html
<div class="panel panel-filled-heading">
  ...
</div>
```

**Comment by danielcollettepb** [comment]
I have something in place for the fix, need to run this by @victorhayes for the visual design:

![image](https://cloud.githubusercontent.com/assets/6116867/11339146/15f64f56-91c6-11e5-83fe-251ea742d88a.png)

**Comment by danielcollettepb** [comment]
@victorhayes is going to mock up examples

**Comment by danielcollettepb** [comment]
@victorhayes here are the revised contextual alternate panel colors as well as the updated contextual alternate backgrounds. Added panel examples for `.panel-info` and `.panel-primary`. Let's review when you have a minute.

![image](https://cloud.githubusercontent.com/assets/6116867/11483996/a8015f4a-9779-11e5-912b-a4edf376635b.png)

![image](https://cloud.githubusercontent.com/assets/6116867/11484008/bad686c2-9779-11e5-87de-8b3496033178.png)

**Comment by victorhayes** [comment]
@danielcollettepb So the thing that is bothering me is that we are mixing Alert styling and Contextual Alternative styling (specifically the text color). Can we discuss this with Carla at our meeting today.
I think if folks are going to use Contextual Alternative Panels that they should have the text in gray.

**Comment by danielcollettepb** [comment]
@victorhayes @cpileggi here are updated panels per our discussion. Let me know if there are any comments:

![image](https://cloud.githubusercontent.com/assets/6116867/11600946/e4177dc6-9a9d-11e5-8fc8-4920e652e139.png)

**Comment by danielcollettepb** [comment]
![2015-12-07_12-47-21](https://cloud.githubusercontent.com/assets/6116867/11634896/40615774-9ce1-11e5-8fce-9c876926249b.gif)

**Comment by victorhayes** [comment]
I think that the icon should be before "Shipping Address".

**Comment by danielcollettepb** [comment]
Moved the icon per @victorhayes comment.

CC: @cpileggi

![image](https://cloud.githubusercontent.com/assets/6116867/11658747/410ac208-9d92-11e5-98fd-1aca2b43860e.png)

**Comment by danielcollettepb** [comment]
new guidance for panels with error is added under Web > User Feedback
