### ISSUE TITLE
Web > User Feedback >  Spot Alerts: Icons are incorrect

### ISSUE THREAD

**Issue by cpileggi** [PBGUX/designsystem#49]
For Error, Warning, and Success. Bold copy needs variations for Error and Info.

**Comment by danielcollettepb** [comment]
@cpileggi please indicate which icons should be used in each Error/Warning/Success. Also not sure what the copy variations should be for error/info.

**Comment by danielcollettepb** [comment]
much better with the new copy and correct icons:

![image](https://cloud.githubusercontent.com/assets/6116867/11380518/8874d29c-92c4-11e5-92f7-41b581ca324b.png)

**Comment by victorhayes** [comment]
Do we want to use the "?" for the "Help" Alert?

**Comment by danielcollettepb** [comment]
Changed the help icon to a question mark, looks OK to me:

![image](https://cloud.githubusercontent.com/assets/6116867/11381534/8fa59992-92ca-11e5-82b8-f6392049caa7.png)

**Comment by victorhayes** [comment]
looks great!

**Comment by cpileggi** [comment]
It looks fine, but I’m questioning the need for a Help Alert. I think the “i” makes sense, but not so much the “?” or the word “Help”.


On Nov 24, 2015, at 3:44 PM, danielcollettepb <notifications@github.com<mailto:notifications@github.com>> wrote:


Changed the help icon to a question mark, looks OK to me:

[image]<https://cloud.githubusercontent.com/assets/6116867/11381534/8fa59992-92ca-11e5-82b8-f6392049caa7.png>

—
Reply to this email directly or view it on GitHub<https://github.com/PBGUX/designsystem/issues/49#issuecomment-159414098>.


________________________________

**Comment by danielcollettepb** [comment]
I reviewed this with Julie and the "?" and the word "Help" are OK. We will commit the code and can discuss later if needed.
