### ISSUE TITLE
Web > Buttons

### ISSUE THREAD

**Issue by cpileggi** [PBGUX/designsystem#50]
Need to add table "Action bar" buttons to DS

**Comment by danielcollettepb** [comment]
@cpileggi can you give some more detail? Maybe add a screenshot of the `Action Bar`, I assume this is to show it in the toolbar...

**Comment by cpileggi** [comment]
Our action bar buttons are a different style than the buttons that are on the button page (Primary, Secondary, Link). We need to add them to our list of buttons. They have a gray stroke and the stroke disappears on hover. We have samples of this style on the table page.

**Comment by danielcollettepb** [comment]
we'll add an exampleof the `.toolbar` from the datatables page to the buttons page in a new section... thanks @cpileggi!

**Comment by danielcollettepb** [comment]
@smlombardi added the example to the buttons page
