### ISSUE TITLE
Table drawer caret

### ISSUE THREAD

**Issue by victorhayes** [PBGUX/designsystem#51]
Caret should be grey (#2e2e2e) instead of blue
http://guxstaging.pbi.global.pvt/design_system/#/tables/datatable (table row details)

**Comment by danielcollettepb** [comment]
@smlombardi @victorhayes  I think we'll have to add a class to the `<a>` on the caret toggle to make it gray... it's not always the first `<td>` and there could be other links in the row, so we can't override it globally. What do you think of adding `.row-toggle` to the `<a>`?:

```html
<td>
   <a href="" class="row-toggle" ng-init="tables.showDetails = true" ng-click="tables.showDetails = !tables.showDetails">
      <i class="fa fa-fw fa-lg fa-angle-right transition-all" ng-class="{'fa-rotate-90': tables.showDetails}" style=""></i>
   </a>
 </td>
```

**Comment by lombardi-gux** [comment]
I thought there already was  toggle class, so that's fine with me

**Comment by danielcollettepb** [comment]
using `.table-row-toggle` since we use `.table-row-selected`

**Comment by danielcollettepb** [comment]
looks good... all examples are updated, also remade the images for paging and infinite-scroll examples. @victorhayes if this looks good I can close this issue.

![image](https://cloud.githubusercontent.com/assets/6116867/11344521/df3b31ce-91df-11e5-9bce-a544c880dcd3.png)

**Comment by victorhayes** [comment]
Looks good to me.


On Nov 23, 2015, at 12:44 PM, danielcollettepb <notifications@github.com<mailto:notifications@github.com>> wrote:


looks good... all examples are updated, also remade the images for paging and infinite-scroll examples. @victorhayes<https://github.com/victorhayes> if this looks good I can close this issue.

[image]<https://cloud.githubusercontent.com/assets/6116867/11344521/df3b31ce-91df-11e5-9bce-a544c880dcd3.png>

—
Reply to this email directly or view it on GitHub<https://github.com/PBGUX/designsystem/issues/51#issuecomment-159008344>.


________________________________

**Comment by danielcollettepb** [comment]
code merged, will be in next release
