### ISSUE TITLE
Typography updates

### ISSUE THREAD

**Issue by victorhayes** [PBGUX/designsystem#52]
In the UI Controls table:
- Remove the active state rows for checkboxes and radio buttons as the text color does not change
- Add input field text
  - entered - #3e53a4
  - placeholder - #9b9b9b
  - disabled - #c0c0c0 (if applicable)
  - read-only - #4e4e4e

**Comment by danielcollettepb** [comment]
Changes are complete, also changed the font family since these are all Helvetica, not Precision Sans. Let me know if this is correct and I can close this item:

![image](https://cloud.githubusercontent.com/assets/6116867/11369632/01a4f778-928e-11e5-80af-38cea2aae49d.png)

**Comment by victorhayes** [comment]
looks great!
