### ISSUE TITLE
'app' module's issue in Draggable modal directive

### ISSUE THREAD

**Issue by ni010go** [PBGUX/designsystem#53]
Draggable modal directive(pbModalDraggable) is created in app module. But, 'app' module is not being created at this place. 
To use it, in my application I have to create 'app' module and then I can use it.
Also, 'app' is a very generic name, so it can create conflict while using it.
As per my opinion, a new module with a more meaningful(e.g: draggable) should be created 
e.g: angular.module('app', []) [in directive js]

This will require no change at my end, also will help integrating if any update comes for the same directive.

**Comment by jrodguitar** [comment]
I would recommend the module name to be pbgux, or some name that will seem somewhat unique.
then under that module (which acts almost like a namespace), we will have all the directives.

**Comment by danielcollettepb** [comment]
Thanks @ni010go and @jrodguitar. We had a discussion a couple weeks ago on creating a module with a unique name, similar to other libraries like ui-bootstrap. We were actually discussing creating directives for the custom checkbox/radio buttons and this same topic was brought up (as well as thoughts on creating a new bower repo for directives or combining them with the pb-design-system).

Currently you will have to edit the directive as noted above.

I'm going to reference this issue in the backlog card for creating directives. This feedback is great, it helps validate the need and backlog sorting. Thanks for contributing!
