### ISSUE TITLE
Directive should be bundled with designsystem package

### ISSUE THREAD

**Issue by ni010go** [PBGUX/designsystem#54]
I was trying to integrate pb-modal-draggable.directive in my application, it is using template elements-draggable-template.html. It has a dependency on ui-bootstrap library. 
The point raised in my team is we should have the component bundled as a  part of dist, so that 
 whenever we upgrade to latest version 
1. we just need to unzip it and replace it in our dependencies. 
2. It will also remove the need to search the dependencies(e.g: templates here) in the complete code on my own.

A Readme can also be added to assist for details of   dependencies and libraries used.

**Comment by danielcollettepb** [comment]
This is related to #53, will add this to the same backlog card for discussion and prioritization. Thanks!
