### ISSUE TITLE
jsTree Theme

### ISSUE THREAD

**Issue by dustin2524** [PBGUX/designsystem#56]
This is not a small request but I think its worth to consider putting on the roadmap. 

We use the [jquery tree plugin jsTree](https://www.jstree.com/demo/).

Currently we have it styled slightly better by using a 3rd party bootstrap 3 theme [https://github.com/orangehill/jstree-bootstrap-theme](https://github.com/orangehill/jstree-bootstrap-theme).

It would be very nice if we didn't have to rely on this 3rd party theme and there are some styles it has that are not the same as the design system. If the DS supported jsTree and had a theme it would be a nice addition to the design system.

We have this tree in many places and heavily rely on it, so I would imagine other teams could use a tree as well. Also, jsTree is not like any other tree component out there, it's has a plugin feature that makes it irreplaceable for us. Here are some instances of it in our app.

![image](https://cloud.githubusercontent.com/assets/4664726/11502618/efda424c-9809-11e5-8684-3c443f2f69d3.png)

![image](https://cloud.githubusercontent.com/assets/4664726/11502631/047cd322-980a-11e5-8717-817826fb743d.png)

![image](https://cloud.githubusercontent.com/assets/4664726/11502653/16ed60f8-980a-11e5-94d3-e61750102345.png)

**Comment by danielcollettepb** [comment]
thanks @dustin2524, I'll add this item to the backlog so we can discuss/prioritize.

Are you using an open source angular directive with jsTree or did you create your own?

**Comment by dustin2524** [comment]
thanks @danielcollettepb . We had to create our own. Angular jsTree libraries that exist are usually not kept up-to-date and typically lack full functionality.

**Comment by danielcollettepb** [comment]
added to backlog and referenced this issue
