### ISSUE TITLE
H3 Font Incorrect

### ISSUE THREAD

**Issue by victorhayes** [PBGUX/designsystem#59]
Change the H3 on Typography page in the Header table:
Should be "H3 = Precision Sans Regular 18"
![screen shot 2015-12-11 at 11 41 43 am](https://cloud.githubusercontent.com/assets/14873269/11749545/689e49cc-9ffc-11e5-8776-0dd73d331489.png)

**Comment by danielcollettepb** [comment]
fixed, will be in next release
