### ISSUE TITLE
Tiered Dropdown Nav Items

### ISSUE THREAD

**Issue by victorhayes** [PBGUX/designsystem#60]
Tiered Dropdown Nav Items - Should be Precision Sans 12pt - #717171
Tiered Dropdown Nav Items (active) - Should be Precision Sans 12pt - #2e2e2e

**Comment by danielcollettepb** [comment]
@victorhayes please provide details on where these changes need to be made

**Comment by danielcollettepb** [comment]
this is on the Web > Typography page

**Comment by danielcollettepb** [comment]
These specs conflict with #61, please indicate which is correct.

**Comment by danielcollettepb** [comment]
discussed with @victorhayes, this issue is incorrect
