### ISSUE TITLE
Navigation Table Font Colors

### ISSUE THREAD

**Issue by victorhayes** [PBGUX/designsystem#61]
Typography / Navigation Table:
- Section Headers (in dropdown): # 2e2e2e - Precision Sans 14pt Reg
- Tiered Dropdown Nav item: # 717171 - Helvetica Neue 12pt Reg
- Tiered Dropdown Nav item Active: # 2e2e2e - Helvetica Neue 12pt Reg
- Side Nav Section Header: # 2e2e2e - Precision Sans 18pt Reg
- Side Nav item: # 717171 - Precision Sans 14pt Reg
- Side Nav hover item: # 2e2e2e - Precision Sans 14pt Reg
- Side Nav active item: # 2e2e2e - Precision Sans 14pt Reg
- Breadcrumbs (previous pages - Link) - # 0072B8 - Helvetica Neue 14pt Reg
- Breadcrumbs (current page) - # C0C0C0 - Helvetica Neue 14pt Reg

**Comment by danielcollettepb** [comment]
discussed with @victorhayes , changes completed
