### ISSUE TITLE
Enhanced Checkboxes are misaligned when used with bootstrap "form-horizontal" class

### ISSUE THREAD

**Issue by nishrana** [PBGUX/designsystem#62]
![image](https://cloud.githubusercontent.com/assets/9932055/12269626/57cb9c8e-b920-11e5-90d3-1ce214861345.png)

**Comment by danielcollettepb** [comment]
Can you post the code for this horizontal form?

**Comment by danielcollettepb** [comment]
Nisha is looking into the issue and will provide a fix.

**Comment by danielcollettepb** [comment]
The last PR fixes the checkboxes, but not the radio buttons:

![image](https://cloud.githubusercontent.com/assets/6116867/12562849/4242cdec-c375-11e5-821f-e1d38f351d05.png)

Please look into this..
