### ISSUE TITLE
Resizable logo

### ISSUE THREAD

**Issue by nickroberts** [PBGUX/designsystem#63]
It would be nice to have a logo that we could resize to any size, via css.

I tried to do this with the current `.pb-footer-logo` class, but, with the `:before` `content` being the data uri, it doesn't resize.

I came up with a solution like this:

```sass
.pb-logo {
  &:before {
    content: " ";
    background-image: url("data:image/svg+xml;base64,<the rest of the data>");
    background-size: cover;
    position: relative;
    display: inline-block;
    height: 46px;
    width: 188px;
  }
}
```

With it like this, we can change the size of the logo, and it scales nicely.

**Comment by danielcollettepb** [comment]
What's the use case for this? Typically we only have the logo in the footer, just curious to where else it is needed... maybe a screenshot?

If we do add this, it should be combined with #64 so that we can have one logo class as the full color logo, with variations of dark and light. Need to think this through so we don't bloat the CSS with three versions of the SVG.

Another thought is to have the logos defined in the Sass only as variables so you can use them if needed, the Design System CSS would only use the logo in the footer.

Thoughts?

**Comment by lombardi-gux** [comment]
We already have the logo, in its approved location and size in color, in black, and in white.  Check the CSS.

I think this is sufficient, as people shouldn't use the logo in arbitrary locations and sizes.

Sent using OWA for iPhone
________________________________

**Comment by nickroberts** [comment]
The use case for what I was going for was a losing screen, which I needed to implement before our app loaded.

Here is what I have right now:
![screen shot 2016-01-20 at 10 50 04 pm](https://cloud.githubusercontent.com/assets/972330/12471553/ae5d6f0c-bfcc-11e5-9418-08ba4f7eddc5.png)

I was thinking something like this would be cool, as well, if we wanted to have a little color:
![screen shot 2016-01-20 at 10 57 12 pm](https://cloud.githubusercontent.com/assets/972330/12471211/72302ad6-bfc9-11e5-8f12-bcf5f64401ae.png)

I found the `.ko` class for the white logo. I didn't see it before.

Do we have any designs for a loading screen, which is pre-app initialization?

**Comment by lombardi-gux** [comment]
You can steal the design of the login screen.  There' s a knockout logo in the footer.

If we find we need to design such a screen, we'd rather do that than just provide resizable logos and leave it to each person.  It would be bettr to have Victor set sizes, and then we provide the sizes in context.  Thanks.

On Jan 20, 2016, at 11:22 PM, nickroberts <notifications@github.com<mailto:notifications@github.com>> wrote:


The use case for what I was going for was a losing screen, which I needed to implement before our app loaded.

Here is what I have right now:
[screen shot 2016-01-20 at 10 50 04 pm]<https://cloud.githubusercontent.com/assets/972330/12471553/ae5d6f0c-bfcc-11e5-9418-08ba4f7eddc5.png>

I was thinking something like this would be cool, as well, if we wanted to have a little color:
[screen shot 2016-01-20 at 10 57 12 pm]<https://cloud.githubusercontent.com/assets/972330/12471211/72302ad6-bfc9-11e5-8f12-bcf5f64401ae.png>

I found the .ko class for the white logo. I didn't see it before.

Do we have any designs for a loading screen, which is pre-app initialization?

—
Reply to this email directly or view it on GitHub<https://github.com/PBGUX/designsystem/issues/63#issuecomment-173447473>.


________________________________

**Comment by nickroberts** [comment]
Makes sense. I'll check out the login screen and go from there. Much appreciated, and keep up the good work!
