### ISSUE TITLE
Can't use pb-button-progress directive with angular translate

### ISSUE THREAD

**Issue by rwoods** [PBGUX/designsystem#68]
Since pb-button-progress and translate directives both use isolated scope, Angular throws an error.  This is kind of important since angular translate is a very popular way of doing localization.

```
        <button type="button"
                class="btn btn-primary"
                pb-button-progress
                ng-click="button.refillLoading.load()"
                ng-model="button.refillLoading"
                ng-disabled="!amount"
                translate="MODALS.ADDFUNDS.BUTTON.DONE">
        </button>

```
`Error: [$compile:multidir] Multiple directives [pbButtonProgress (module: pbOotbWebApp), translate (module: pascalprecht.translate)] asking for new/isolated scope on: <button type="button" class="btn btn-primary ng-pristine ng-untouched ng-valid" pb-button-progress="" ng-click="button.refillLoading.load()" ng-model="button.refillLoading" ng-disabled="!amount" translate="MODALS.ADDFUNDS.BUTTON.DONE">`

**Comment by rwoods** [comment]
As a workaround to unblock us for now, in the pb-button-progress.directive.js, instead of copying the element.text to the scope.ngModel.defaultText, instead I pass in my translated button label as part of ngModel and copy that to scope.ngModel.defaultText. Then I use the translate service to do my translation in my controller instead of using the translate directive on the button itself.  Probably not ideal for a final solution in pbgux, but it works for us. Maybe you could add .label to your ngModel options and make a check in your directive if it's set, use it instead of element.text?  For ref here is my modified version of your directive.


```
(function() {

  'use strict';

  angular.module('pbOotbWebApp').directive('pbButtonProgress', function() {
      return {
        restrict: 'A',
        require: 'ngModel',
        scope: {
          ngModel: '='
        },
        link: function postLink(scope, element, attrs, ngModel) {

          //store the set button label
          scope.ngModel.defaultText = scope.ngModel.label ? scope.ngModel.label : element.text();

          //set the default fa-icon
          var icon = (scope.ngModel.iconClass) ? scope.ngModel.iconClass : scope.ngModel.iconClass = 'fa-circle-o-notch';

          //set the default speed
          var speed = (scope.ngModel.speed) ? scope.ngModel.speed : scope.ngModel.speed = 1.5;

          scope.$watch('ngModel.isLoading', function(newVal, oldVal) {
            if (newVal) {
              element.addClass('loading');
              element.text(scope.ngModel.text);
              element.prepend('<i class="fa ' + icon + ' fa-spin"></i>&nbsp;&nbsp;');
              element.find('i.fa').css({
                '-webkit-animation': 'fa-spin ' + speed + 's infinite linear',
                animation: 'fa-spin ' + speed + 's infinite linear'
              });
              element.prop('disabled', true);
            } else {
              element.removeClass('loading');
              element.text(scope.ngModel.defaultText);
              element.prop('disabled', false);
            }
          });
        }
      };
    });

})();

```

**Comment by danielcollettepb** [comment]
thanks for the feedback @rwoods, I took a slightly different approach and injected `$translate` in the controller to set the text in the model, no changes to the directive. See 9161dfd7923e55e99f503a1d558572d28e995582

```javascript
angular.module('pb.ds.feedback').controller('ProgressController', function($log, $timeout, cfpLoadingBar, $translate) {

...

_this.buttonLoading = {
      isLoading: false,
      defaultText: '',
      text: '',
      load: function() {
        _this.buttonLoading.isLoading = true;
        $timeout(function() {
          _this.buttonLoading.isLoading = false;
        }, 2000);
      }
    };

    //example setting the text states with globalization strings
    $translate('BUTTONS.SAVE').then(function(string) {
      _this.buttonLoading.defaultText = string;
    });

    $translate('BUTTONS.SAVING').then(function(string) {
      _this.buttonLoading.text = string;
    });
```

Let me know what you think...

**Comment by rwoods** [comment]
That's exactly what I'm doing in my controller as well, but instead of setting .defaultText I was adding a new parameter .label.  But doesn't the directive overwrite .defaultText with element.text()?

**Comment by danielcollettepb** [comment]
In the html I removed the text and the strings are empty in the model, $translate is setting the text afterwards

**Comment by rwoods** [comment]
I still can't get it to work with your proposed solution.  In my controller, I'm setting this..

```
    $scope.button = {
      defaultText: '',
      text: '',
      isLoading: false,
      speed: 0.75,
      iconClass: 'fa-refresh',
      load: function () {
        $scope.button.isLoading = true;
        $scope.showErrorMessage = false;
        data.amount = $scope.amount;

        metersModel.performRefill({meterId: meterId}, data,
          function (result) {
              $scope.button.isLoading = true;
              $scope.showErrorMessage = false;
              $modalInstance.close(result);
          },
          function (result) {
            $scope.button.isLoading = false;
            switch (result.status) {
              case 500: // Service unavailable
                $scope.showErrorMessage = true;
                break;
              case 401: // Unauthorized
                AuthSvc.checkAuth($state.current.name);
                break;
              case 404: // Not found
                $scope.showErrorMessage = true;
                break;
              default:  // All others
                $scope.showErrorMessage = true;
                break;
            }
          });
      }
    };

```

And then I set the defaultText and text like this

```
    $translate(['MODALS.ADDFUNDS.BUTTON.DONE',
                'MODALS.ADDFUNDS.BUTTON.SAVING']).then(function(translation) {
      $scope.button.defaultText = translation['MODALS.ADDFUNDS.BUTTON.DONE'];
      $scope.button.text = translation['MODALS.ADDFUNDS.BUTTON.SAVING'];
    });

```

And HTML
```
        <button type="button"
                class="btn btn-primary icon-left"
                pb-button-progress
                ng-click="button.load()"
                ng-model="button"
                ng-disabled="!amount"
                ng-bind="button.defaultText">
        </button>

```

I just get empty text on the button.  If I step into the directive, I see that scope.ngModel.defaultText has my correct string, but then  this line overwrites it with basically an empty string.

`          scope.ngModel.defaultText = element.text();
`

If I comment out that line in the directive it works.

**Comment by danielcollettepb** [comment]
Hmmm... I don't see that on my end stepping through. Instead of commenting out that line try:

```javascript
scope.ngModel.defaultText = (!scope.ngModel.defaultText) ? scope.ngModel.defaultText : element.text();
```

I also don't have `ng-bind` in my html... added it but it didn't have any effect either.

I'm going to add this to our backlog, not only for your issue, but there are things we can do better in this directive (using a template and binding to properties to update the template rather than using jQuery, etc)

**Comment by jrnorrisjr** [comment]
I have not tried this but what if you try to use the translate filter instead of the directive does that work?

<button type="button"
    class="btn btn-primary"
    pb-button-progress
    ng-click="button.refillLoading.load()"
    ng-model="button.refillLoading"
    ng-disabled="!amount">
    {{'MODALS.ADDFUNDS.BUTTON.DONE' | translate}}
</button>

**Comment by danielcollettepb** [comment]
This directive was rewritten in 3.0 and now works with angular-translate.

It will be part of `pb.ds.components` in the bower install.
