### ISSUE TITLE
Definition list top margin is not 0

### ISSUE THREAD

**Issue by du002cl** [PBGUX/designsystem#7]
It seems there is a style added to description list titles \<dt> of margin-top: 10px; 
This is fine but this causes the entire list \<dl> appear to have a margin-top: 10px, since the topmost \<dt> has the top margin.

![dl](https://cloud.githubusercontent.com/assets/10408154/5880656/2e9b1eae-a308-11e4-8a06-dffb8758064a.jpg)

Applying margin-top:-10px to \<dl> solves this.
Applying margin-top:0px to the first \<dt> would also solve this.

**Comment by smlombardi** [comment]
Fixed 250a9a8eeb8797df005210d4ae947f40b7aeee6d
