### ISSUE TITLE
Date Picker Calendar Icon

### ISSUE THREAD

**Issue by andygrossman** [PBGUX/designsystem#73]
Our current date pickers are only editable when a user clicks on the printed date, which opens the calendar or range controls. Most people try to click on the calendar _icon_ first but the icon is not clickable. Can we make the calendar icon open the calendar as well?

![2016-03-01_14-55-19](https://cloud.githubusercontent.com/assets/5264416/13440026/19363816-dfbe-11e5-8ca3-023a0f6b1e7a.png)

**Comment by danielcollettepb** [comment]
@lombardi-gux please add this as a JIRA ticket

**Comment by smlombardi** [comment]
This will be in the 2.6 release.
