### ISSUE TITLE
Bootstrap Thumbnail Class Overwrites

### ISSUE THREAD

**Issue by du002cl** [PBGUX/designsystem#8]
We are trying to use the bootstrap thumbnail class shown here http://getbootstrap.com/components/#thumbnails

and in context...
![thumbnail1](https://cloud.githubusercontent.com/assets/10408154/6027644/818b292c-abb1-11e4-876a-f619115fd23b.png)

When we tried to add this it seems the designsystem.css already had a thumbnail class that overwrote most of bootstraps rules. Currently we are just overwriting those rules to get back to bootstrap standards for the thumbnail class. Should the thumbnail class that exists be changed, or another class added that we can use for our image border?

**Comment by smlombardi** [comment]
There are no thumbnail classes in design_system.css 1.02

**Comment by du002cl** [comment]
Thank you.
