### ISSUE TITLE
Transitory Alert - need a persistent version

### ISSUE THREAD

**Issue by rcianfag** [PBGUX/designsystem#80]
We need a version of the transitory alert that is conditional based on a user action, not dismissing automatically.

**Comment by smlombardi** [comment]
We will look into adding an example. However, any developer could re-purpose the existing one easily to respond to an event instead of a timer. Thanks.

**Comment by danielcollettepb** [comment]
Example added in 3.0. Note that the directive is completely rewritten and will be bundled in the `pb.ds.components`.

Also added an example showing how to set the duration to `0` (zero) to keep the message displayed.
