### ISSUE TITLE
White space added with the svg icons in 2.5

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/designsystem#81]
I updated the relay hub application to conform to the DS 2.5 header with the SVG icons.  At first I added the  SVG tags at the end of the body and the result was a large white space below the footer and a vertical scroll bar.  I tried moving the SVG tags to the top of the body and that caused the whitespace (about 160px) to appear between the header and the content area and again the scroll bar.  Any advice on where the SVG tags should be placed to overcome this?

**Comment by jrnorrisjr** [comment]
I also tried putting them inside the header tag and that made the header 200+ pixels high

**Comment by jrnorrisjr** [comment]
I'm pretty sure the white space between the last footer example and the actual footer on the DS web site is because that's where the svg tags are.

**Comment by rdukeshier** [comment]
<svg width="0" height="0"> worked for me.

**Comment by jrnorrisjr** [comment]
Where did you place them?

**Comment by smlombardi** [comment]
@rdukeshier Good idea.

You can also take the SVG tags for each icon out of the `defs` and use them in their final position (where I have `use` tags)

**Comment by jrnorrisjr** [comment]
Thanks Steve, I'll give that a try

**Comment by smlombardi** [comment]
@jrnorrisjr What browser did you see this issue in?

**Comment by jrnorrisjr** [comment]
@smlombardi  it was chrome.  I did as you suggested and do not have the issue now

**Comment by smlombardi** [comment]
That's good to know.  Thanks.

**Comment by smlombardi** [comment]
@jrnorrisjr  @rdukeshier I have since discovered you can simply set the `svg` tag in the defs block to `display:none`, as in 
```html
<svg style="display:none;">
  <defs>
     ...
```
