### ISSUE TITLE
Footer styles don't get applied when using container-fluid

### ISSUE THREAD

**Issue by SamSwartzPB** [PBGUX/designsystem#82]
Not sure if this is by design or not, but it looks a little strange when forced to use a container with an otherwise fluid site.

The Following HTML results in the image I've attached:

```
<div class="footer-wrapper">
	<div class="container-fluid">
	  <div class="contents">
	    <!-- the logo and copyright have their own flexbox -->
	    <div class="logo-copyright">
	      <div class="footer-logo"><a href="http://www.pb.com"><i class="pb-footer-logo gradient"></i></a></div>
	      <div class="copyright">© 2016 Pitney Bowes Inc.</div>
	    </div>
	    <div class="t-and-c"><a href="">Terms and conditions</a></div>
	  </div>
	</div>
</div>
```

![image](https://cloud.githubusercontent.com/assets/10424009/13613306/8b677c44-e539-11e5-8043-bd60f248c114.png)

**Comment by smlombardi** [comment]
Fixed in https://github.com/PBGUX/designsystem/commit/b851849c953085f4ecd87a17c4c70d033209ffc1
