### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/designsystem#83]
We are migrating away from bower in favor of npm (which we already use for build dependencies).  Can we get pb-design-system registered with npm?

**Comment by smlombardi** [comment]
We will add it to the backlog as a future enhancement. Thanks.

**Comment by du002cl** [comment]
+1

**Comment by danielcollettepb** [comment]
@rdukeshier @du002cl please try installing with `npm install pb-design-system` and let us know if this works.

@smlombardi  we'll have to update the readme in the next release with NPM instructions and bump the package.json version too, please add these to the release checklist

**Comment by rdukeshier** [comment]
Works like a champ.  Thanks all.

**Comment by danielcollettepb** [comment]
I tried adding `bootstrap` as a dependency like we do with the bower.json but npm installs it in a `node_modules` folder under `pb-design-system`. *I suggest we don't do this... Thoughts?*

![image](https://cloud.githubusercontent.com/assets/6116867/13958085/2b53f0e8-f025-11e5-9ade-36cc4ea2256b.png)

Also, `npm` does not allow you to publish over an already published semver (bower does)... so I had to bump the package.json version to test this out, will have to bump it once more if we decide to remove the dependency. We'll make the next release (2.6 ay end of month) the first with npm support.

**Comment by rdukeshier** [comment]
What version of npm are you using?  I thought the latest version was supposed to install dependencies in the top-most node_modules dir whenever possible (i.e. when no versioning conflicts exist).  We already have bootstrap configured as a dependency, so it definitely did not nest in my local install.

**Comment by danielcollettepb** [comment]
thanks for the info @rdukeshier, I updated to the latest node/npm and it now installs as intended:

![image](https://cloud.githubusercontent.com/assets/6116867/13980440/fe83a1ae-f0b4-11e5-80d7-86ef722a5c00.png)

@smlombardi we'll need to document this too
