### ISSUE TITLE
Radio button control indicator looks off-center

### ISSUE THREAD

**Issue by SamSwartzPB** [PBGUX/designsystem#85]
Looks like the current styling of the background size is `background-size: 50% 50%`. This makes the control-indicator look off centered to the bottom right.

![image](https://cloud.githubusercontent.com/assets/10424009/13717785/f39251a2-e7b1-11e5-8a91-5394c456da16.png)

If you change the background size to be 75% `background-size: 75%` the control-indicator looks correct

![image](https://cloud.githubusercontent.com/assets/10424009/13717806/266f0da4-e7b2-11e5-8152-bb2be93bfb06.png)

**Comment by smlombardi** [comment]
I cannot repro this in Chrome 51, Safari 9, IE11 or IE Edge
