### ISSUE TITLE
issue with navbar collapse

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/designsystem#87]
When the horizontal size of the relay hub application is reduced the menu items to right side disappear but the menu items to left remain.  At some point after reducing the horizontal size the links on the right disappear and the hamburger icon appears in the upper right corner.  The brand remains.  Clicking on the hamburger icon does nothing.  Has this been an issue with other apps?

**Comment by smlombardi** [comment]
This is  a known issue, and we are working on it.

**Comment by jrnorrisjr** [comment]
Thanks for the update Steve

**Comment by smlombardi** [comment]
We are going to implement it, at least as a phase one, by adding it to the bottom of the existing mobile menu on design system (which you can see be viewing the site on phone or in the gif below)

![mobile menu](https://cloud.githubusercontent.com/assets/835148/13858095/69b856ec-ec53-11e5-84e6-e4f511854712.gif)

**Comment by smlombardi** [comment]
This is in the upcoming 2.6 release.
