### ISSUE TITLE
Need priority-based Message Card Styles

### ISSUE THREAD

**Issue by rcianfag** [PBGUX/designsystem#88]
Need priority-based Message Card Styles

- Info
- Urgent
![ssto-trial message card](https://cloud.githubusercontent.com/assets/11758386/13782808/0bad5c10-ea9f-11e5-8100-42bd4c2f5e8d.png)
<img width="739" alt="ssto-info_messagecard" src="https://cloud.githubusercontent.com/assets/11758386/13782871/4dd01d80-ea9f-11e5-9f15-ed61ac8aada5.png">

**Comment by lombardi-gux** [comment]
Do you need these as toasters, as shown in your mockups?

**Comment by smlombardi** [comment]
Also. if you want these as inline (in the html page) dismissible alerts, these already exist in the Design System, see http://localhost:3000/#/feedback#alerts

The developers can easily override the background color to white and add the icon:

![screen shot 2016-03-15 at 11 41 21 am(https://cloud.githubusercontent.com/assets/835148/13783794/31e870c8-eaa3-11e5-894b-22fae7140db0.png)

![screen shot 2016-03-15 at 11 41 34 am](https://cloud.githubusercontent.com/assets/835148/13783803/37a1a886-eaa3-11e5-8215-f6ffdbc4b2d0.png)

**Comment by rcianfag** [comment]
Not quite toastr behavior - the trial messages are displayed by default and the user will be able to dismiss them. They will expand multiple rows, and have different priorities.
We expect these to be the first 'Message Cards' for SSTO, Dev has been asking if there is a style.

**Comment by smlombardi** [comment]
you can do this with toasters.  they can be opened on page load, and they can stay open until dismissed.  If more than one is called, they stack up.

We do not have a graphic style that looks like what you have yet, but the existing toaster styles can be overridden.

http://guxstaging.pbi.global.pvt/design_system/#/feedback#toastrs
