### ISSUE TITLE
.alert-link class needs to be manually applied

### ISSUE THREAD

**Issue by rnavarette** [PBGUX/designsystem#9]
How about changing the rule for styling links in alert messages to not require explicitly adding the 'alert-link' class?

Since we're using a link embedded in a translation (which requires us sending html embedded in the string to translators), I'd like to keep the formatting to a minimum.  And, I think this would be a fine change in general.

So
```html
    <div class="alert alert-info"><a href="#">Click here</a></div>
```
instead of
```html
    <div class="alert alert-info"><a class="alert-link" href="#">Click here</a></div>
```

**Comment by smlombardi** [comment]
You shouldn't need to.  In the [sass for the alerts](https://github.com/PBGUX/designsystem/blob/master/app/sass/elements/_notifications.scss) you can see that all the text inside an alert is the alert's text color.  Except info, where it was decided it wasn't dark enough so we added  code to darken the link automatically.  If you think it's needed, I can add a similar method for the other alerts.


````
//* alerts */
.alert-danger {
  background-color: $state-danger-bg;
  border-color: $state-danger-border;
  color: $state-danger-text;
}
.alert-success {
  background-color: $state-success-bg;
  border-color: $state-success-border;
  color: $state-success-text;
}
.alert-warning {
  background-color: $state-warning-bg;
  border-color: $state-warning-border;
  color: $state-warning-text;
}
.alert-info {
  background-color: $state-info-bg;
  border-color: $state-info-border;
  color: $state-info-text;
  a {
    color: darken($link-color, 20%);
  }
}
````

**Comment by smlombardi** [comment]
Clarified the alerts page and removed that class ob the link  Thanks.

See 72e69d48ad5938b77db04e1fde0bdc13347896b1

**Comment by rnavarette** [comment]
Thanks for checking into this...

I think the issue is not the color, but the font-weight though.  In the compiled css:
```css
.alert .alert-link {
    font-weight: bold;
}
```
Can we just update the weight on ".alert a"?

**Comment by smlombardi** [comment]
I will need to check with the art director.  I know we were trying to avoid using bold.

**Comment by lombardi-gux** [comment]
It was decided to make those links be underlined.  This was added in ae23e95491bfd5839fe816450f732fe2810147ec

**Comment by rnavarette** [comment]
The link appears only on hover.  Is that intended?  Especially on the 'info' style, the links in normal (non-hover) state are quite difficult to discern.

**Comment by lombardi-gux** [comment]
Fixed in 1.1.2   bb4d0550fe754d22c1caaeeed0a25cf4727c4354

**Comment by rnavarette** [comment]
thanks.  Just checking... did you want that to be 1.12?

**Comment by lombardi-gux** [comment]
no i have been told I should use the 2 dots...  thanks, though.
