### ISSUE TITLE
Faceted Search Demo Alignment Issues

### ISSUE THREAD

**Issue by rcollette** [PBGUX/designsystem#94]
![screen shot 2016-04-01 at 1 37 00 pm](https://cloud.githubusercontent.com/assets/136476/14215125/00afbd6c-f80f-11e5-8b2c-c39a32b4c41c.png)

See the page number (I think) alignment in the lower right of the image.
http://guxstaging.pbi.global.pvt/design_system/#/tables/facetedsearch

**Comment by danielcollettepb** [comment]
The column pull for the paging is incorrect, it should be `col-md-pull-2` which will place it under the table:

![image](https://cloud.githubusercontent.com/assets/6116867/14217017/d1affe40-f819-11e5-9de9-a8ca047d0f11.png)


![image](https://cloud.githubusercontent.com/assets/6116867/14217041/eee56608-f819-11e5-9e21-b7b7a279db37.png)

**Comment by smlombardi** [comment]
Fixed in https://github.com/PBGUX/designsystem/commit/b60b86eaa4a1a0f6a4c660aa3896e6d93cbcd73b
