### ISSUE TITLE
Make button focus more prominent

### ISSUE THREAD

**Issue by rcianfag** [PBGUX/designsystem#95]
Feedback from SSTO team:
Make the button focus more prominent - currently using the Hover state, change of darker blue not obvious.
- Consider adding 
![button focus](https://cloud.githubusercontent.com/assets/11758386/14248046/61ac47ba-fa40-11e5-9135-08df0aa4c375.png)
shadow similar to the field focus

**Comment by smlombardi** [comment]
We will look into our options.

Note, also, that the drawback is once a button is clicked with a mouse the focus state sticks until something else is given focus.

**Comment by danielcollettepb** [comment]
@rcianfag are you looking specifically for the mouse "hover" or keyboard "focus"? (or maybe both)... we have another story to look into the keyboard "focus" state

**Comment by smlombardi** [comment]
this is done, as of 2.8
